apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9OaWhhbDpob21lcmVudGFsQGNsdXN0ZXIwLnBnMW5xLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJmFwcE5hbWU9Q2x1c3RlcjA=
  RAPIDAPI_KEY: MzQ4NjE3NDhjNG1zaGZlYmFjZmExN2ZjNjFmcDE0NWZhYWpzbmE4ZWU2ZjY4ZmJiMg==
  SECRET_KEY: MTIzNDU=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVF1U3NiMkxkWld6VFk5ZHk2TGxJUDZQUVBkQ3JxYnU1QWJhMWxWRWtzSUljbjIxcURaRFFEcWs3VFNBRmtkVWNpODJ0bGNVeFMyMjAxT3RMWGFTTWhmZzAwZDRVS1JNc2U=
